#!/usr/bin/env node
import {
  existsSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";

interface Args {
  repo: string;
  skillsDir: string;
  output: string;
  source: string;
  title: string;
}

interface SkillInfo {
  dirName: string;
  name: string;
  description: string;
}

const META_SKILL_NAMES = new Set(["shared-skill-repository", "skill-builder"]);

function parseArgs(argv: string[]): Args {
  const args: Args = {
    repo: process.cwd(),
    skillsDir: "skills",
    output: "README.md",
    source: "",
    title: "byway agent skills",
  };

  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    const next = () => {
      const value = argv[++i];
      if (!value) throw new Error(`Missing value for ${arg}`);
      return value;
    };

    if (arg === "--repo") args.repo = next();
    else if (arg === "--skills-dir") args.skillsDir = next();
    else if (arg === "--output") args.output = next();
    else if (arg === "--source") args.source = next();
    else if (arg === "--title") args.title = next();
    else if (arg === "--help" || arg === "-h") usage(0);
    else throw new Error(`Unknown argument: ${arg}`);
  }

  if (!args.source) {
    throw new Error(
      "Missing required --source <owner/repo-or-git-url> for install commands",
    );
  }

  return args;
}

function usage(code: number): never {
  const stream = code === 0 ? process.stdout : process.stderr;
  stream.write(
    `Usage: node generate-readme.ts --repo <repo-dir> --source <owner/repo-or-git-url> [options]\n\nOptions:\n  --repo <dir>          Shared skills repo directory (default: current directory)\n  --skills-dir <dir>    Skills directory inside repo (default: skills)\n  --output <file>       README path inside repo (default: README.md)\n  --source <source>     Install source shown in npx skills commands\n  --title <title>       README title (default: byway agent skills)\n  -h, --help            Show this help\n`,
  );
  process.exit(code);
}

function parseFrontmatter(markdown: string): Record<string, string> {
  if (!markdown.startsWith("---\n")) return {};
  const end = markdown.indexOf("\n---", 4);
  if (end === -1) return {};

  const yaml = markdown.slice(4, end).trim();
  const values: Record<string, string> = {};
  for (const line of yaml.split(/\r?\n/)) {
    const match = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!match) continue;
    const [, key, rawValue] = match;
    values[key] = rawValue.trim().replace(/^['"]|['"]$/g, "");
  }
  return values;
}

function escapeMarkdownCell(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/\r?\n/g, " ").trim();
}

function discoverSkills(skillsRoot: string): SkillInfo[] {
  if (!existsSync(skillsRoot)) {
    throw new Error(`Skills directory does not exist: ${skillsRoot}`);
  }

  return readdirSync(skillsRoot)
    .filter((entry) => {
      const fullPath = path.join(skillsRoot, entry);
      return (
        statSync(fullPath).isDirectory() &&
        existsSync(path.join(fullPath, "SKILL.md"))
      );
    })
    .map((dirName) => {
      const skillPath = path.join(skillsRoot, dirName, "SKILL.md");
      const frontmatter = parseFrontmatter(readFileSync(skillPath, "utf8"));
      return {
        dirName,
        name: frontmatter.name || dirName,
        description: frontmatter.description || "",
      };
    })
    .sort((a, b) => a.name.localeCompare(b.name));
}

function skillRows(args: Args, skills: SkillInfo[]): string {
  const rows = skills.map((skill) => {
    const installCommand = `npx skills add ${args.source} --skill ${skill.name}`;
    return `| \`${escapeMarkdownCell(skill.name)}\` | ${escapeMarkdownCell(skill.description)} | \`${escapeMarkdownCell(installCommand)}\` |`;
  });

  return rows.length ? rows.join("\n") : "| _No skills found_ |  |  |";
}

function skillTable(args: Args, skills: SkillInfo[]): string {
  return `| Skill | Description | Install command |\n| --- | --- | --- |\n${skillRows(args, skills)}`;
}

function buildReadme(args: Args, skills: SkillInfo[]): string {
  const metaSkills = skills.filter((skill) => META_SKILL_NAMES.has(skill.name));
  const regularSkills = skills.filter(
    (skill) => !META_SKILL_NAMES.has(skill.name),
  );

  return `# ${args.title}\n\nShared Agent Skills repository installable with Vercel's Skills CLI.\n\n## Skills\n\n${skillTable(args, regularSkills)}\n\n## Meta-Skills\n\nMeta-skills help create, publish, and maintain this shared skill repository.\n\n${skillTable(args, metaSkills)}\n\n## Repository layout\n\n\`\`\`text\nskills/<skill-name>/SKILL.md\n\`\`\`\n\nREADME generated by \`shared-skill-repository/scripts/generate-readme.ts\`.\n`;
}

try {
  const args = parseArgs(process.argv.slice(2));
  const repo = path.resolve(args.repo);
  const skillsRoot = path.resolve(repo, args.skillsDir);
  const outputPath = path.resolve(repo, args.output);
  const skills = discoverSkills(skillsRoot);
  writeFileSync(outputPath, buildReadme(args, skills));
  console.log(`Generated ${outputPath} with ${skills.length} skill(s).`);
} catch (error) {
  console.error(error instanceof Error ? error.message : error);
  usage(1);
}
